version: '3'
services:
  consul-server:
    image: consul
    container_name: consul-server
    ports:
      - 8500:8500
    command: consul agent -server -bootstrap-expect=1 -ui -client=0.0.0.0 -data-dir=/consul/data
    volumes:
      - ./consul-data:/consul/data
    networks:
      - consul-network

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: K9A1qfhb1pWZV186eJasTE9kgrHLMTRzaaHnSjQ8RzVNvlashE
      MONGO_INITDB_ROOT_DATABASE: ${MONGO_ROOT_DB:-mongodb}
      MONGO_INITDB_DATABASE: init  # arbitrary value
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d/

networks:
  consul-network:
